#!/bin/bash

# Script to generate Python SDK from OpenAPI specification
# Usage: ./generate-sdk.sh

set -e

# Configuration
OPENAPI_URL="${OPENAPI_URL:-http://localhost:8080/api/v1/swagger.json}"
GENERATOR_VERSION="${GENERATOR_VERSION:-7.9.0}"
PACKAGE_NAME="leapocr-python"
OUTPUT_DIR="./src/leapocr/gen"

echo "🎯 Generating Python SDK for LeapOCR..."
echo "📡 OpenAPI URL: $OPENAPI_URL"

# Create temp directory
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Step 1: Download full OpenAPI spec
echo "📋 Step 1: Downloading OpenAPI spec..."
curl -s "$OPENAPI_URL" > "$TEMP_DIR/openapi-full.json"

# Step 2: Filter SDK endpoints
echo "📋 Step 2: Filtering SDK endpoints..."
./scripts/filter-sdk-endpoints.sh "$TEMP_DIR/openapi-full.json" "$TEMP_DIR/openapi-sdk.json"

# Step 3: Generate Python client
echo "📋 Step 3: Generating Python client..."
docker run --rm \
    -v "$TEMP_DIR:/local" \
    openapitools/openapi-generator-cli:v$GENERATOR_VERSION generate \
    -i /local/openapi-sdk.json \
    -g python-pydantic-v1 \
    -o /local/generated-python \
    --skip-validate-spec \
    --additional-properties=packageName=openapi_client,generateSourceCodeOnly=true,library=urllib3,disallowAdditionalPropertiesIfNotPresent=true,hideGenerationTimestamp=true

# Step 4: Clean and organize generated files
echo "📋 Step 4: Organizing generated files..."
rm -rf "$OUTPUT_DIR/openapi_client"
mkdir -p "$OUTPUT_DIR"

# Copy generated client files
cp -r "$TEMP_DIR/generated-python/openapi_client" "$OUTPUT_DIR/"

# Clean up unnecessary files
find "$OUTPUT_DIR" -name "*.py" -not -path "*/openapi_client/*" -delete
find "$OUTPUT_DIR" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
rm -f "$OUTPUT_DIR"/*.md "$OUTPUT_DIR"/*.txt "$OUTPUT_DIR"/.gitignore

# Step 5: Fix imports and add proper __init__.py
echo "📋 Step 5: Fixing generated code..."
cat > "$OUTPUT_DIR/openapi_client/__init__.py" << 'EOF'
"""
Generated OpenAPI client for LeapOCR API.

This module contains auto-generated client code from the OpenAPI specification.
Do not edit this file directly.
"""

# Import main client and models for easier access
from .client import LeapOCRGenClient
from .configuration import Configuration
from .exceptions import ApiException

__all__ = ["LeapOCRGenClient", "Configuration", "ApiException"]
EOF

# Step 6: Generate validation script
cat > "$TEMP_DIR/validate_generation.py" << 'EOF'
#!/usr/bin/env python3
"""Simple validation script for generated SDK."""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

try:
    from leapocr.gen.openapi_client import LeapOCRGenClient
    print("✅ Generated client imports successfully")
    
    # Test basic client instantiation
    config = LeapOCRGenClient.Configuration()
    print("✅ Client configuration works")
    
    # Check if we have the expected models
    models_dir = os.path.join(os.path.dirname(__file__), '..', 'src', 'leapocr', 'gen', 'openapi_client', 'models')
    if os.path.exists(models_dir):
        model_files = [f for f in os.listdir(models_dir) if f.endswith('.py') and not f.startswith('__')]
        print(f"✅ Generated {len(model_files)} model files")
    else:
        print("❌ Models directory not found")
        sys.exit(1)
        
except ImportError as e:
    print(f"❌ Import error: {e}")
    sys.exit(1)
except Exception as e:
    print(f"❌ Validation error: {e}")
    sys.exit(1)
EOF

python3 "$TEMP_DIR/validate_generation.py"

echo "✅ SDK generation complete!"
echo ""
echo "📦 Generated files:"
echo "   - Client: $OUTPUT_DIR/openapi_client/client.py"
echo "   - Models: $OUTPUT_DIR/openapi_client/models/"
echo "   - Configuration: $OUTPUT_DIR/openapi_client/configuration.py"
echo ""
echo "📋 Next steps:"
echo "   1. Implement wrapper client in src/leapocr/client.py"
echo "   2. Add custom exceptions in src/leapocr/exceptions.py"
echo "   3. Create service classes in src/leapocr/services/"
echo "   4. Update main __init__.py to expose public API"